#ddev-generated

services:
    # mount certificate folder to website
    web:
        volumes:
            - elastic-certs:/usr/share/elasticsearch/config/certs

    elastic-config:
        container_name: ddev-${DDEV_SITENAME}-elastic-config
        hostname: ${DDEV_SITENAME}-elastic-config
        image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
        volumes:
            - ".:/mnt/ddev_config"
            - elastic-certs:/usr/share/elasticsearch/config/certs
        environment:
            - ELASTIC_PASSWORD=elastic
            - KIBANA_PASSWORD=elastic
        labels:
            com.ddev.site-name: ${DDEV_SITENAME}
            com.ddev.approot: $DDEV_APPROOT
        user: "0"
        restart: "no"
        command: >
            bash -c '
                echo "Waiting for Elasticsearch availability";
                until curl -s -u elastic:elastic http://elasticsearch:9200; do sleep 5 && date; done;

                echo "Setting kibana_system password";
                until curl -s -X POST -u elastic:elastic -H "Content-Type: application/json" http://elasticsearch:9200/_security/user/kibana_system/_password -d "{\"password\":\"elastic\"}" | grep -q "^{}"; do sleep 5 && date ; done;

                echo "Testing kibana_system user";
                until curl -s -u kibana_system:elastic http://elasticsearch:9200; do sleep 5 && date; done;

                echo "Exit in 5 minutes"
                for i in {1..5}; do date && sleep 60; done

                echo "All done!";
              '

    elasticsearch:
        depends_on:
            - elastic-config
        image: elasticsearch:8.12.0
        volumes:
            - ./enterprise-search/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - elastic-certs:/usr/share/elasticsearch/config/certs
            - elasticsearch:/usr/share/elasticsearch/data
        environment:
            - cluster.name=docker-cluster
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - VIRTUAL_HOST=$DDEV_HOSTNAME
            - HTTP_EXPOSE=9200:9200
            - HTTPS_EXPOSE=9201:9200
            - ELASTIC_PASSWORD=elastic
            - KIBANA_PASSWORD=elastic
        healthcheck:
            disable: true

    kibana:
        depends_on:
            - elasticsearch
            - elastic-config
        # Name of container using standard ddev convention
        container_name: ddev-${DDEV_SITENAME}-kibana
        hostname: ${DDEV_SITENAME}-kibana
        image: docker.elastic.co/kibana/kibana:8.12.0
        volumes:
            - ".:/mnt/ddev_config"
            - ./enterprise-search/kibana.yml:/usr/share/kibana/config/kibana.yml
            - elastic-certs:/usr/share/kibana/config/certs
            - elastic-kibana:/usr/share/kibana/data
        # These labels ensure this service is discoverable by ddev.
        labels:
            com.ddev.site-name: ${DDEV_SITENAME}
            com.ddev.approot: $DDEV_APPROOT
        expose:
            - "5601"
        environment:
            - VIRTUAL_HOST=$DDEV_HOSTNAME
            - SERVERNAME=kibana
            - KIBANA_PASSWORD=elastic
            - HTTP_EXPOSE=5601:5601
            - HTTPS_EXPOSE=5602:5601
        mem_limit: 1073741824
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "curl -s -I http://kibana:5601 | grep -q 'HTTP/1.1 302 Found'",
                ]
            interval: 10s
            timeout: 10s
            retries: 120

    enterprisesearch:
        depends_on:
            - elasticsearch
            - kibana
        container_name: ddev-${DDEV_SITENAME}-enterprisesearch
        hostname: ${DDEV_SITENAME}-enterprisesearch
        image: docker.elastic.co/enterprise-search/enterprise-search:8.12.0
        volumes:
            - ".:/mnt/ddev_config"
            - ./enterprise-search/config.yml:/usr/share/enterprise-search/config/enterprise-search.yml
            - elastic-certs:/usr/share/enterprise-search/config/certs
            - enterprise-data:/usr/share/enterprise-search/config
        # These labels ensure this service is discoverable by ddev.
        labels:
            com.ddev.site-name: ${DDEV_SITENAME}
            com.ddev.approot: $DDEV_APPROOT
        environment:
            - VIRTUAL_HOST=$DDEV_HOSTNAME
            - SERVERNAME=enterprisesearch
            - ELASTIC_PASSWORD=elastic
            - KIBANA_PASSWORD=elastic
        mem_limit: 2147483648
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "curl -s -I http://enterprisesearch:3002 | grep -q 'HTTP/1.1 302 Found'",
                ]
            interval: 10s
            timeout: 10s
            retries: 120

volumes:
    elastic-certs:
    elastic-data:
    elastic-kibana:
    enterprise-data:
    elasticsearch:
